global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: spring-actuator # add a job to scrape from spring boot app locally
    metrics_path: "/acutator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8080"]
